apiVersion: v1
kind: Service
metadata:
  name: store-engine-orchestrator-queue-go-ms-service
spec:
  selector:
    app: store-engine-orchestrator-queue-go-ms
  ports:
    - protocol: TCP
      port: 3050
      targetPort: 3050
  type: NodePort
  
